modifying colored_img_generator to loop over known colors.
OpenStitching/stitching pull request #100
Opened 2023-06-22 09:09 UTC by KaceCM

Before this correction, the function raised "ValueError("Not enough default colors! Pass additional " 'colors to "colors" parameter')", but we couldn't pass additional colors.

To avoid this problem and to make it easier, the correction takes the 9 known colors (Blue, Red, Green, Yellow, Magenta, Pink, Gray, Brown, Orange), and loop over them if needed.

2023-06-22 15:36 UTC, lukasalexanderweber commented
Thanks! Can we keep the error message anyway?

2023-06-22 15:44 UTC, lukasalexanderweber commented
Or what exactly is idx%len(colors) doing? Just repeating the first color after the last one is reached?

2023-06-22 16:04 UTC, KaceCM commented
Yes of course we can keep the message, I'm going to add a couple of lines to make it even better.

idx%len(colors) means that, for a given tuple "colors", if the number of images is longer than this tuple length, it will repeat from the first color.
I had a problem using 20 images, so I did this correction and thought it would be useful for people !

By the way, thank you for this insane package !

2023-06-22 17:09 UTC, KaceCM commented
I have added a warning message, with instructions for those who wish to add their own colours. Otherwise, it loops the default colors.

Let me know if anything is missing, or if you need anything else !

2023-06-22 18:01 UTC, lukasalexanderweber requested changes
Thank you very much for reaching out to fix this for many images. Clever idea with the use of Modulo for repeating colors. Sorry for the bad formatting, im on the Smartphone

2023-06-23 09:47 UTC, KaceCM commented
I have now corrected all your requests, tell me if everything is correct now !

2023-06-23 10:24 UTC, merged

2023-06-23 10:25 UTC, lukasalexanderweber commented
Thanks a lot! :)